//
// Created by anarion on 6/9/19.
//

#ifndef CPPFOREST_SINGLEVARIABLEROOTFINDER_H
#define CPPFOREST_SINGLEVARIABLEROOTFINDER_H


class SingleVariableRootFinder {

};


#endif //CPPFOREST_SINGLEVARIABLEROOTFINDER_H
